# Generated by Django 5.2.4 on 2026-10-05 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_seed_team"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutPageContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(default="About Sunrise Drilling", max_length=200),
                ),
                (
                    "subtitle",
                    models.CharField(
                        default="Your trusted partner for water solutions and drilling services in Kenya",
                        max_length=255,
                    ),
                ),
                ("intro", models.TextField(default="")),
                (
                    "journey_title",
                    models.CharField(default="Our Journey", max_length=200),
                ),
                (
                    "journey_subtitle",
                    models.CharField(
                        default="A timeline of our growth and achievements",
                        max_length=255,
                    ),
                ),
                (
                    "values_title",
                    models.CharField(default="Our Values", max_length=200),
                ),
                (
                    "values_subtitle",
                    models.CharField(
                        default="The principles that guide everything we do",
                        max_length=255,
                    ),
                ),
                ("mission_text", models.TextField(default="")),
                ("vision_text", models.TextField(default="")),
                (
                    "cert_title",
                    models.CharField(
                        default="Certifications and Compliance", max_length=200
                    ),
                ),
                (
                    "cert_subtitle",
                    models.CharField(
                        default="Our commitment to quality and regulatory standards",
                        max_length=255,
                    ),
                ),
                ("cert_intro", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name": "About Page",
                "verbose_name_plural": "About Page",
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=255)),
                ("answer", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQs",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="GalleryPageContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "header_title",
                    models.CharField(default="Our Gallery", max_length=200),
                ),
                (
                    "header_subtitle",
                    models.CharField(
                        default="Explore our portfolio of successful projects and see the quality of our work",
                        max_length=255,
                    ),
                ),
                (
                    "categories_title",
                    models.CharField(default="Project Categories", max_length=200),
                ),
                (
                    "categories_subtitle",
                    models.CharField(
                        default="Explore our diverse range of water solution projects",
                        max_length=255,
                    ),
                ),
                (
                    "achievements_title",
                    models.CharField(default="Our Achievements", max_length=200),
                ),
            ],
            options={
                "verbose_name": "Gallery Page",
                "verbose_name_plural": "Gallery Page",
            },
        ),
        migrations.CreateModel(
            name="HomePageContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hero_title",
                    models.CharField(default="Sunrise Drilling", max_length=200),
                ),
                (
                    "hero_subtitle",
                    models.CharField(
                        default="Expert Drilling Services", max_length=200
                    ),
                ),
                ("hero_location", models.CharField(default="In Kenya", max_length=200)),
                (
                    "hero_button_text",
                    models.CharField(default="CONTACT US", max_length=50),
                ),
                (
                    "services_title",
                    models.CharField(default="Our Services", max_length=200),
                ),
                (
                    "services_subtitle",
                    models.CharField(
                        default="The areas we are working on are:", max_length=255
                    ),
                ),
                (
                    "cta_title",
                    models.CharField(
                        default="Ready to Start Your Project?", max_length=200
                    ),
                ),
                (
                    "cta_subtitle",
                    models.CharField(
                        default="Get in touch with us today for expert drilling services and water solutions",
                        max_length=255,
                    ),
                ),
                (
                    "cta_button_text",
                    models.CharField(default="Contact Us Today", max_length=50),
                ),
            ],
            options={
                "verbose_name": "Home Page",
                "verbose_name_plural": "Home Page",
            },
        ),
        migrations.CreateModel(
            name="HomeServiceCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        help_text="Font Awesome class, e.g. fa-water", max_length=50
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Home Service Card",
                "verbose_name_plural": "Home Service Cards",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="InquiryType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Contact Inquiry Type",
                "verbose_name_plural": "Contact Inquiry Types",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="QuickLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        help_text="Font Awesome class, e.g. fa-users", max_length=50
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=200)),
                (
                    "page",
                    models.CharField(
                        choices=[
                            ("main:home", "Home"),
                            ("main:about", "Who we are"),
                            ("main:team", "Team"),
                            ("main:services", "Services"),
                            ("main:gallery", "Gallery"),
                            ("main:contact", "Contact"),
                        ],
                        default="main:contact",
                        max_length=30,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Home Quick Link",
                "verbose_name_plural": "Home Quick Links",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ServicesPageContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "header_title",
                    models.CharField(default="Our Services", max_length=200),
                ),
                (
                    "header_subtitle",
                    models.CharField(
                        default="Comprehensive solutions for all your drilling, construction, and supply needs",
                        max_length=255,
                    ),
                ),
                (
                    "intro_title",
                    models.CharField(
                        default="The areas we are working on are:", max_length=255
                    ),
                ),
                (
                    "process_title",
                    models.CharField(default="Our Process", max_length=200),
                ),
                (
                    "process_subtitle",
                    models.CharField(
                        default="How we deliver exceptional results for every project",
                        max_length=255,
                    ),
                ),
                (
                    "why_title",
                    models.CharField(
                        default="Why Choose Sunrise Drilling?", max_length=200
                    ),
                ),
                (
                    "why_subtitle",
                    models.CharField(
                        default="What sets us apart in the industry", max_length=255
                    ),
                ),
            ],
            options={
                "verbose_name": "Services Page",
                "verbose_name_plural": "Services Page",
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        default="sunrisedrillingltd@gmail.com", max_length=254
                    ),
                ),
                (
                    "phone_primary",
                    models.CharField(default="+254 720 997 769", max_length=30),
                ),
                (
                    "phone_secondary",
                    models.CharField(
                        blank=True, default="+254 728 821 642", max_length=30
                    ),
                ),
                (
                    "physical_address",
                    models.CharField(
                        default="G737+69Q, Rivatex road, Ndovu lane, Pioneer, Eldoret, Kenya",
                        max_length=255,
                    ),
                ),
                (
                    "postal_address",
                    models.CharField(
                        default="P.O. BOX 9630-30100, ELDORET", max_length=255
                    ),
                ),
                (
                    "website",
                    models.CharField(
                        default="www.sunrisedrillingltd.com", max_length=100
                    ),
                ),
                (
                    "business_hours",
                    models.TextField(
                        default="Monday - Friday: 8:00 AM - 6:00 PM\nSaturday: 9:00 AM - 4:00 PM\nSunday: Emergency services only\nEmergency: 24/7 Available",
                        help_text="One line per entry; shown on the contact page",
                    ),
                ),
                (
                    "map_embed_url",
                    models.TextField(
                        blank=True,
                        help_text="Google Maps embed URL for the contact page map",
                    ),
                ),
                (
                    "map_title",
                    models.CharField(
                        default="Sunrise Drilling Ltd Headquarters", max_length=200
                    ),
                ),
                (
                    "map_address",
                    models.TextField(
                        default="G737+69Q, Rivatex road, Ndovu lane, Pioneer\nEldoret, Uasin Gishu County, Kenya"
                    ),
                ),
                ("facebook_url", models.URLField(blank=True)),
                ("instagram_url", models.URLField(blank=True)),
                ("twitter_url", models.URLField(blank=True)),
                ("tiktok_url", models.URLField(blank=True)),
                (
                    "copyright_text",
                    models.CharField(
                        default="Sunrise Drilling. All rights reserved", max_length=200
                    ),
                ),
            ],
            options={
                "verbose_name": "Site Settings",
                "verbose_name_plural": "Site Settings",
            },
        ),
        migrations.CreateModel(
            name="TeamPageContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("header_title", models.CharField(default="Our Team", max_length=200)),
                (
                    "header_subtitle",
                    models.CharField(
                        default="The people behind Kenya's trusted water solutions",
                        max_length=255,
                    ),
                ),
                (
                    "cta_title",
                    models.CharField(default="Want to work with us?", max_length=200),
                ),
                (
                    "cta_subtitle",
                    models.CharField(
                        default="Talk to our team about your water project today.",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "verbose_name": "Team Page",
                "verbose_name_plural": "Team Page",
            },
        ),
        migrations.CreateModel(
            name="TimelineEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.CharField(help_text="e.g. 2019 or 2022-2025", max_length=20),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "icon",
                    models.CharField(
                        default="fa-rocket",
                        help_text="Font Awesome class, e.g. fa-rocket",
                        max_length=50,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Timeline Event",
                "verbose_name_plural": "Timeline Events",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ValueCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("value", "Our Values"),
                            ("certification", "Certifications & Compliance"),
                        ],
                        default="value",
                        max_length=20,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        help_text="Font Awesome class, e.g. fa-handshake", max_length=50
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "About Value / Certification Card",
                "verbose_name_plural": "About Value / Certification Cards",
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="contactpagecontent",
            name="email_note",
            field=models.CharField(
                default="We respond to all emails within 24 hours", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="contactpagecontent",
            name="faq_subtitle",
            field=models.CharField(
                default="Common questions about our services", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="contactpagecontent",
            name="faq_title",
            field=models.CharField(
                default="Frequently Asked Questions", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="contactpagecontent",
            name="form_subtitle",
            field=models.CharField(
                default="Please fill the form below and we will get back to you as soon as possible",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="contactpagecontent",
            name="form_title",
            field=models.CharField(default="Send Us a Message", max_length=200),
        ),
        migrations.AddField(
            model_name="contactpagecontent",
            name="map_section_subtitle",
            field=models.CharField(
                default="Our location in Eldoret, Kenya", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="contactpagecontent",
            name="map_section_title",
            field=models.CharField(default="Find Us", max_length=200),
        ),
        migrations.AddField(
            model_name="contactpagecontent",
            name="phone_note",
            field=models.CharField(
                default="Available 24/7 for emergency services", max_length=255
            ),
        ),
    ]
