# Generated by Django 5.2.4 on 2026-10-06 08:50

import business.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0002_invoice_invoiceitem_payment_project_projectnote"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="pdf_file",
            field=models.FileField(
                blank=True,
                help_text="Saved copy of the last PDF emailed to the client",
                upload_to=business.models.invoice_pdf_path,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="pdf_file",
            field=models.FileField(
                blank=True,
                help_text="Saved copy of the last receipt PDF emailed to the client",
                upload_to=business.models.receipt_pdf_path,
            ),
        ),
        migrations.AddField(
            model_name="proposal",
            name="pdf_file",
            field=models.FileField(
                blank=True,
                help_text="Saved copy of the last PDF emailed to the client",
                upload_to=business.models.proposal_pdf_path,
            ),
        ),
    ]
